services:
  ollama:
    build:
      context: .
      args:
        OLLAMA_VERSION: latest
        HF_REPO: unsloth/Qwen3-4B-Instruct-2507-GGUF
        QUANT: Q4_K_M
    container_name: ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "ollama show qwen3-4b >/dev/null 2>&1 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  ollama:
